export const ICON_DICT: Record<string, string> = {
  crab: '🦀', octopus: '🐙', shark: '🦈', whale: '🐋', dolphin: '🐬',
  shrimp: '🦐', squid: '🦑', lobster: '🦞', jellyfish: '🪼',
  worm: '🪱', snake: '🐍', spider: '🕷️', ant: '🐜', bee: '🐝',
  butterfly: '🦋', beetle: '🪲', scorpion: '🦂', mosquito: '🦟',
  frog: '🐸', lizard: '🦎', turtle: '🐢', crocodile: '🐊', dinosaur: '🦖',
  eagle: '🦅', owl: '🦉', penguin: '🐧', parrot: '🦜',
  bat: '🦇', wolf: '🐺', fox: '🦊', bear: '🐻', tiger: '🐅',
  lion: '🦁', elephant: '🐘', monkey: '🐒', deer: '🦌',
  volcano: '🌋', planet: '🪐', galaxy: '🌌',
  meteor: '☄️', rocket: '🚀', satellite: '🛰️',
  comet: '☄️', asteroid: '🪨', nebula: '🌌',
  brain: '🧠', dna: '🧬', bone: '🦴',
  tooth: '🦷', skull: '💀',
  lightning: '⚡', tornado: '🌪️',
  microscope: '🔬', telescope: '🔭',
  vent: '💨', diamond: '💎', crystal: '💎',
  egg: '🥚', mushroom: '🍄',
};
